kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team-a-ns1
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-east, cluster-central
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]