apiVersion: v1
kind: Namespace
metadata:
  name: team-a-ns1
  annotations:
    configmanagement.gke.io/cluster-selector: cluster-east
  labels:
    istio.io/rev: asm-managed
    istio-injection: enabled